%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2


imu_topic: "/mavros/imu/data_raw"
image0_topic: "/camera/infra1/image_rect_raw"
image1_topic: "/camera/infra2/image_rect_raw"




output_path: "/home/kexie/vins_output"


cam0_calib: "left.yaml"
cam1_calib: "right.yaml"
image_width: 640
image_height: 480
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -6.8560613573507290e-03, -1.6299492252085385e-01,
       9.8660308617755954e-01, 1.3637182093674535e-01,
       -9.9978254000202482e-01, 2.0548725254497135e-02,
       -3.5528295082506434e-03, 1.0639197973974049e-02,
       -1.9694342582674440e-02, -9.8641289788953790e-01,
       -1.6310036096649272e-01, 4.7270373671866824e-02, 0., 0., 0., 1. ]
body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -7.2921759109956241e-03, -1.6311818136859912e-01,
       9.8657958780702759e-01, 1.3400125700100204e-01,
       -9.9978205021857791e-01, 2.0489897319538097e-02,
       -4.0020205611929760e-03, -3.8361821274985983e-02,
       -1.9562112135977028e-02, -9.8639374643944100e-01,
       -1.6323204573227645e-01, 4.6598124598357812e-02, 0., 0., 0., 1. ]         
# body_T_cam0: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [ 7.3031794151823259e-04, -1.6631830798260822e-01,
#        9.8607184680707038e-01, 1.3295465448148197e-01,
#        -9.9969214449827604e-01, 2.4334019074038871e-02,
#        4.8447646116269727e-03, 1.5356433390590287e-02,
#        -2.4800864181355797e-02, -9.8577181738245412e-01,
#        -1.6624933440573919e-01, 5.4021080521741441e-02, 0., 0., 0., 1. ]
# body_T_cam1: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [ 2.3085487210217082e-04, -1.6639792432165773e-01,
#        9.8605865823868322e-01, 1.3120143027851036e-01,
#        -9.9969617581046522e-01, 2.4265550377060352e-02,
#        4.3288722353474474e-03, -3.2868442498696027e-02,
#        -2.4647571400843005e-02, -9.8576006910725611e-01,
#        -1.6634176678663182e-01, 5.2887042047288411e-02, 0., 0., 0., 1. ]


#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.001         # accelerometer bias random work noise standard deviation.  #0.002
gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.805         # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: -0.05                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/fast/savedfiles/output/pose_graph/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 

